import React from 'react';
import { motion } from 'framer-motion';
import { Brain, Cpu, MessageSquare, LineChart, ChevronRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useApi } from '../context/ApiContext';
import ApiKeySetup from '../components/ApiKeySetup';

const FeatureCard = ({ icon: Icon, title, description, path, color }) => (
    <motion.div
        whileHover={{ y: -5 }}
        className="relative p-6 rounded-2xl bg-white dark:bg-gray-800 shadow-xl border border-gray-100 dark:border-gray-700 overflow-hidden group"
    >
        <div className={`absolute top-0 right-0 w-24 h-24 -mr-8 -mt-8 rounded-full bg-${color}-500/10 group-hover:bg-${color}-500/20 transition-colors`} />
        <div className={`p-3 rounded-xl bg-${color}-500/10 w-fit mb-4`}>
            <Icon className={`h-8 w-8 text-${color}-500`} />
        </div>
        <h3 className="text-xl font-bold mb-2">{title}</h3>
        <p className="text-gray-600 dark:text-gray-400 mb-6">{description}</p>
        <Link
            to={path}
            className={`flex items-center text-${color}-500 font-semibold group-hover:gap-2 transition-all`}
        >
            Explore <ChevronRight className="h-4 w-4" />
        </Link>
    </motion.div>
);

const LandingPage = () => {
    const { isConfigured } = useApi();

    if (!isConfigured) {
        return (
            <div className="pt-32 pb-20">
                <div className="text-center mb-12 px-4">
                    <h1 className="text-4xl md:text-7xl font-black mb-6 tracking-tighter bg-gradient-to-r from-blue-500 to-purple-600 bg-clip-text text-transparent">AI Campus Mentor</h1>
                    <p className="text-gray-500 max-w-lg mx-auto text-lg">Master Data Structures, Algorithms, and Core CSE subjects with your personalized AI coach.</p>
                </div>
                <ApiKeySetup />
            </div>
        );
    }

    return (
        <div className="pt-20">
            {/* Hero Section */}
            <section className="px-4 py-20 text-center max-w-7xl mx-auto">
                <motion.h1
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="text-5xl md:text-7xl font-extrabold mb-6 tracking-tight"
                >
                    Master Your <br />
                    <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                        Campus Placements
                    </span>
                </motion.h1>
                <motion.p
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, delay: 0.2 }}
                    className="text-lg md:text-xl text-gray-600 dark:text-gray-400 mb-10 max-w-2xl mx-auto"
                >
                    A AI-powered practice platform for students. Practice Quantitative, Logical Reasoning,
                    CSE Core concepts, and ace your Technical Interviews.
                </motion.p>
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, delay: 0.4 }}
                    className="flex flex-col sm:flex-row items-center justify-center gap-4"
                >
                    <Link
                        to="/aptitude"
                        className="px-8 py-4 rounded-full bg-blue-600 hover:bg-blue-700 text-white font-bold transition-all shadow-lg hover:scale-105 active:scale-95"
                    >
                        Start Practicing
                    </Link>
                    <Link
                        to="/dashboard"
                        className="px-8 py-4 rounded-full bg-white dark:bg-gray-800 text-gray-900 dark:text-white font-bold border-2 border-gray-200 dark:border-gray-700 transition-all hover:border-blue-500 shadow-md"
                    >
                        Check Performance
                    </Link>
                </motion.div>
            </section>

            {/* Features Grid */}
            <section className="px-4 py-20 max-w-7xl mx-auto">
                <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
                    <FeatureCard
                        icon={Brain}
                        title="Aptitude"
                        description="Quant, Logical, and Verbal reasoning tests generated by AI."
                        path="/aptitude"
                        color="blue"
                    />
                    <FeatureCard
                        icon={Cpu}
                        title="CSE Core"
                        description="Deep dive into DBMS, OS, Computer Networks, and OOPS."
                        path="/cse"
                        color="indigo"
                    />
                    <FeatureCard
                        icon={MessageSquare}
                        title="Mock Interview"
                        description="Real-time feedback on your technical answers with Gemini AI."
                        path="/interview"
                        color="purple"
                    />
                    <FeatureCard
                        icon={LineChart}
                        title="Dashboard"
                        description="Track your progress, see your weak areas, and level up."
                        path="/dashboard"
                        color="teal"
                    />
                </div>
            </section>

            {/* AI Integration Section */}
            <section className="px-4 py-20 bg-gray-100 dark:bg-gray-800/50">
                <div className="max-w-4xl mx-auto text-center">
                    <div className="inline-block p-4 rounded-3xl bg-blue-500/10 mb-8 border border-blue-500/20">
                        <span className="text-blue-500 font-bold text-sm tracking-widest uppercase">Powered by Google Gemini</span>
                    </div>
                    <h2 className="text-3xl md:text-4xl font-bold mb-6">AI-Generated Personalization</h2>
                    <p className="text-lg text-gray-600 dark:text-gray-400">
                        We use the latest Google Gemini model to generate fresh, unique placement-level questions
                        and provide detailed, intelligent feedback on your technical interview performance.
                    </p>
                </div>
            </section>
        </div>
    );
};

export default LandingPage;
